/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExemploRouteImport } from './routes/exemplo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelClientesRouteImport } from './routes/_authenticated/painel.clientes'
import { Route as AuthenticatedPainelEmpresaRouteImport } from './routes/_authenticated/painel.empresa'
import { Route as AuthenticatedPainelPlanoRouteImport } from './routes/_authenticated/painel.plano'
import { Route as AuthenticatedPainelServicosRouteImport } from './routes/_authenticated/painel.servicos'
import { Route as AuthenticatedPainelOrcamentosIndexRouteImport } from './routes/_authenticated/painel.orcamentos.index'
import { Route as AuthenticatedPainelOrcamentosIdRouteImport } from './routes/_authenticated/painel.orcamentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemploRoute = ExemploRouteImport.update({
  id: '/exemplo',
  path: '/exemplo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelClientesRoute =
  AuthenticatedPainelClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelEmpresaRoute =
  AuthenticatedPainelEmpresaRouteImport.update({
    id: '/empresa',
    path: '/empresa',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelPlanoRoute =
  AuthenticatedPainelPlanoRouteImport.update({
    id: '/plano',
    path: '/plano',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelServicosRoute =
  AuthenticatedPainelServicosRouteImport.update({
    id: '/servicos',
    path: '/servicos',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelOrcamentosIndexRoute =
  AuthenticatedPainelOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelOrcamentosIdRoute =
  AuthenticatedPainelOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/empresa': typeof AuthenticatedPainelEmpresaRoute
  '/painel/plano': typeof AuthenticatedPainelPlanoRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/painel/orcamentos/': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/painel/empresa': typeof AuthenticatedPainelEmpresaRoute
  '/painel/plano': typeof AuthenticatedPainelPlanoRoute
  '/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/painel/orcamentos': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/_authenticated/painel/clientes': typeof AuthenticatedPainelClientesRoute
  '/_authenticated/painel/empresa': typeof AuthenticatedPainelEmpresaRoute
  '/_authenticated/painel/plano': typeof AuthenticatedPainelPlanoRoute
  '/_authenticated/painel/servicos': typeof AuthenticatedPainelServicosRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/_authenticated/painel/orcamentos/': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/admin'
    | '/painel'
    | '/orcamento/$token'
    | '/painel/clientes'
    | '/painel/empresa'
    | '/painel/plano'
    | '/painel/servicos'
    | '/painel/'
    | '/painel/orcamentos/$id'
    | '/painel/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/admin'
    | '/orcamento/$token'
    | '/painel/clientes'
    | '/painel/empresa'
    | '/painel/plano'
    | '/painel/servicos'
    | '/painel'
    | '/painel/orcamentos/$id'
    | '/painel/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/painel'
    | '/orcamento/$token'
    | '/_authenticated/painel/clientes'
    | '/_authenticated/painel/empresa'
    | '/_authenticated/painel/plano'
    | '/_authenticated/painel/servicos'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/orcamentos/$id'
    | '/_authenticated/painel/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExemploRoute: typeof ExemploRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplo': {
      id: '/exemplo'
      path: '/exemplo'
      fullPath: '/exemplo'
      preLoaderRoute: typeof ExemploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/clientes': {
      id: '/_authenticated/painel/clientes'
      path: '/clientes'
      fullPath: '/painel/clientes'
      preLoaderRoute: typeof AuthenticatedPainelClientesRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/empresa': {
      id: '/_authenticated/painel/empresa'
      path: '/empresa'
      fullPath: '/painel/empresa'
      preLoaderRoute: typeof AuthenticatedPainelEmpresaRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/plano': {
      id: '/_authenticated/painel/plano'
      path: '/plano'
      fullPath: '/painel/plano'
      preLoaderRoute: typeof AuthenticatedPainelPlanoRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/servicos': {
      id: '/_authenticated/painel/servicos'
      path: '/servicos'
      fullPath: '/painel/servicos'
      preLoaderRoute: typeof AuthenticatedPainelServicosRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/orcamentos/': {
      id: '/_authenticated/painel/orcamentos/'
      path: '/orcamentos'
      fullPath: '/painel/orcamentos/'
      preLoaderRoute: typeof AuthenticatedPainelOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/orcamentos/$id': {
      id: '/_authenticated/painel/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/painel/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedPainelOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelClientesRoute: typeof AuthenticatedPainelClientesRoute
  AuthenticatedPainelEmpresaRoute: typeof AuthenticatedPainelEmpresaRoute
  AuthenticatedPainelPlanoRoute: typeof AuthenticatedPainelPlanoRoute
  AuthenticatedPainelServicosRoute: typeof AuthenticatedPainelServicosRoute
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedPainelOrcamentosIdRoute: typeof AuthenticatedPainelOrcamentosIdRoute
  AuthenticatedPainelOrcamentosIndexRoute: typeof AuthenticatedPainelOrcamentosIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelClientesRoute: AuthenticatedPainelClientesRoute,
  AuthenticatedPainelEmpresaRoute: AuthenticatedPainelEmpresaRoute,
  AuthenticatedPainelPlanoRoute: AuthenticatedPainelPlanoRoute,
  AuthenticatedPainelServicosRoute: AuthenticatedPainelServicosRoute,
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedPainelOrcamentosIdRoute: AuthenticatedPainelOrcamentosIdRoute,
  AuthenticatedPainelOrcamentosIndexRoute:
    AuthenticatedPainelOrcamentosIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExemploRoute: ExemploRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
