/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ExemploRouteImport } from './routes/exemplo'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as OrcamentoTokenRouteImport } from './routes/orcamento.$token'
import { Route as AuthenticatedPainelIndexRouteImport } from './routes/_authenticated/painel.index'
import { Route as AuthenticatedPainelOrcamentosIndexRouteImport } from './routes/_authenticated/painel.orcamentos.index'
import { Route as AuthenticatedPainelOrcamentosIdRouteImport } from './routes/_authenticated/painel.orcamentos.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ExemploRoute = ExemploRouteImport.update({
  id: '/exemplo',
  path: '/exemplo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OrcamentoTokenRoute = OrcamentoTokenRouteImport.update({
  id: '/orcamento/$token',
  path: '/orcamento/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPainelIndexRoute =
  AuthenticatedPainelIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelOrcamentosIndexRoute =
  AuthenticatedPainelOrcamentosIndexRouteImport.update({
    id: '/orcamentos/',
    path: '/orcamentos/',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)
const AuthenticatedPainelOrcamentosIdRoute =
  AuthenticatedPainelOrcamentosIdRouteImport.update({
    id: '/orcamentos/$id',
    path: '/orcamentos/$id',
    getParentRoute: () => AuthenticatedPainelRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/painel': typeof AuthenticatedPainelRouteWithChildren
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/painel/': typeof AuthenticatedPainelIndexRoute
  '/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/painel/orcamentos/': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/painel': typeof AuthenticatedPainelIndexRoute
  '/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/painel/orcamentos': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/exemplo': typeof ExemploRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRouteWithChildren
  '/orcamento/$token': typeof OrcamentoTokenRoute
  '/_authenticated/painel/': typeof AuthenticatedPainelIndexRoute
  '/_authenticated/painel/orcamentos/$id': typeof AuthenticatedPainelOrcamentosIdRoute
  '/_authenticated/painel/orcamentos/': typeof AuthenticatedPainelOrcamentosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/painel'
    | '/orcamento/$token'
    | '/painel/'
    | '/painel/orcamentos/$id'
    | '/painel/orcamentos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/orcamento/$token'
    | '/painel'
    | '/painel/orcamentos/$id'
    | '/painel/orcamentos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/exemplo'
    | '/privacidade'
    | '/reset-password'
    | '/_authenticated/painel'
    | '/orcamento/$token'
    | '/_authenticated/painel/'
    | '/_authenticated/painel/orcamentos/$id'
    | '/_authenticated/painel/orcamentos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ExemploRoute: typeof ExemploRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  OrcamentoTokenRoute: typeof OrcamentoTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exemplo': {
      id: '/exemplo'
      path: '/exemplo'
      fullPath: '/exemplo'
      preLoaderRoute: typeof ExemploRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/orcamento/$token': {
      id: '/orcamento/$token'
      path: '/orcamento/$token'
      fullPath: '/orcamento/$token'
      preLoaderRoute: typeof OrcamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/painel/': {
      id: '/_authenticated/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof AuthenticatedPainelIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/orcamentos/': {
      id: '/_authenticated/painel/orcamentos/'
      path: '/orcamentos'
      fullPath: '/painel/orcamentos/'
      preLoaderRoute: typeof AuthenticatedPainelOrcamentosIndexRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
    '/_authenticated/painel/orcamentos/$id': {
      id: '/_authenticated/painel/orcamentos/$id'
      path: '/orcamentos/$id'
      fullPath: '/painel/orcamentos/$id'
      preLoaderRoute: typeof AuthenticatedPainelOrcamentosIdRouteImport
      parentRoute: typeof AuthenticatedPainelRoute
    }
  }
}

interface AuthenticatedPainelRouteChildren {
  AuthenticatedPainelIndexRoute: typeof AuthenticatedPainelIndexRoute
  AuthenticatedPainelOrcamentosIdRoute: typeof AuthenticatedPainelOrcamentosIdRoute
  AuthenticatedPainelOrcamentosIndexRoute: typeof AuthenticatedPainelOrcamentosIndexRoute
}

const AuthenticatedPainelRouteChildren: AuthenticatedPainelRouteChildren = {
  AuthenticatedPainelIndexRoute: AuthenticatedPainelIndexRoute,
  AuthenticatedPainelOrcamentosIdRoute: AuthenticatedPainelOrcamentosIdRoute,
  AuthenticatedPainelOrcamentosIndexRoute:
    AuthenticatedPainelOrcamentosIndexRoute,
}

const AuthenticatedPainelRouteWithChildren =
  AuthenticatedPainelRoute._addFileChildren(AuthenticatedPainelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPainelRoute: AuthenticatedPainelRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ExemploRoute: ExemploRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  OrcamentoTokenRoute: OrcamentoTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
