name: Verificar Orçai

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código
        uses: actions/checkout@v4
      - name: Preparar Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Instalar dependências
        run: bun install --frozen-lockfile
      - name: Executar testes
        run: bun run test
      - name: Compilar aplicação
        run: bun run build